import React from 'react';
import {
  Box,
  Button,
  TextField,
  Typography,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  CircularProgress,
  Paper,
  Chip,
  Alert,
  InputAdornment,
} from '@mui/material';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import SendIcon from '@mui/icons-material/Send';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import LocationOnIcon from '@mui/icons-material/LocationOn';
import SecurityIcon from '@mui/icons-material/Security';
import { Switch, FormControlLabel } from '@mui/material';

export const AutoFillReviewStep = ({
  title,
  setTitle,
  description,
  setDescription,
  category,
  setCategory,
  photoPreview,
  aiSuccess,
  aiFillUpEnabled,
  address,
  setAddress,
  latitude,
  longitude,
  privacyLock = false,
  setPrivacyLock,
  accountPrivacyLockActive = false,
  dummyAlias = 'LongGiraffe',
  onSubmit,
  onBack,
  submitting,
}) => {
  return (
    <Box sx={{ maxWidth: 650, mx: 'auto' }}>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
        <Typography variant="h6" fontWeight="700">
          Step 2: Review & Submit Report
        </Typography>
        {aiFillUpEnabled && aiSuccess && (
          <Chip
            icon={<AutoAwesomeIcon fontSize="small" />}
            label="Auto-filled by AI"
            color="primary"
            variant="outlined"
            size="small"
            sx={{ fontWeight: 600 }}
          />
        )}
      </Box>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
        {aiFillUpEnabled && aiSuccess
          ? 'Review and edit the report details generated by AI before submitting to public record.'
          : 'Provide a title, category, and description for the reported infrastructure issue.'}
      </Typography>

      {aiFillUpEnabled && !aiSuccess && (
        <Alert severity="warning" sx={{ mb: 3 }}>
          AI auto-fill did not return details. Please fill in the report details manually below.
        </Alert>
      )}

      {/* Photo Summary Thumbnail */}
      {photoPreview && (
        <Paper
          elevation={0}
          sx={{
            p: 1.5,
            mb: 3,
            display: 'flex',
            alignItems: 'center',
            gap: 2,
            border: '1px solid',
            borderColor: 'divider',
            borderRadius: '4px',
          }}
        >
          <Box
            component="img"
            src={photoPreview}
            alt="Report photo thumbnail"
            sx={{ width: 80, height: 60, borderRadius: 1, objectFit: 'cover' }}
          />
          <Typography variant="body2" color="text.secondary">
            Photo ready for submission
          </Typography>
        </Paper>
      )}

      <Box component="form" onSubmit={onSubmit} noValidate>
        <TextField
          margin="normal"
          required
          fullWidth
          id="title"
          label="Report Title"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="e.g. Deep Pothole on Main Street near 5th Ave"
          helperText="Provide a short, clear summary of the issue."
        />

        <FormControl fullWidth margin="normal" required>
          <InputLabel id="category-select-label">Category</InputLabel>
          <Select
            labelId="category-select-label"
            id="category"
            value={category}
            label="Category"
            onChange={(e) => setCategory(e.target.value)}
          >
            <MenuItem value="pothole">Pothole</MenuItem>
            <MenuItem value="streetlight">Streetlight</MenuItem>
            <MenuItem value="traffic_light">Traffic Light</MenuItem>
            <MenuItem value="garbage">Garbage / Dumping</MenuItem>
            <MenuItem value="other">Other Infrastructure</MenuItem>
          </Select>
        </FormControl>

        <TextField
          margin="normal"
          fullWidth
          id="address"
          label="Location Address"
          value={address || ''}
          onChange={(e) => setAddress(e.target.value)}
          placeholder="e.g. Main Bazaar Road, Palayamkottai"
          helperText={
            latitude && longitude
              ? `GPS: ${latitude.toFixed(4)}, ${longitude.toFixed(4)}`
              : 'Auto-detected from GPS pin'
          }
          InputProps={{
            startAdornment: (
              <InputAdornment position="start">
                <LocationOnIcon fontSize="small" color="primary" />
              </InputAdornment>
            ),
          }}
        />

        <TextField
          margin="normal"
          required
          fullWidth
          multiline
          rows={4}
          id="description"
          label="Detailed Description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="Describe the problem, hazard potential, and surrounding details..."
        />

        {/* Privacy Lock Toggle */}
        <Paper
          elevation={0}
          sx={{
            p: 2,
            mt: 2.5,
            borderRadius: 2,
            bgcolor: (theme) =>
              privacyLock
                ? theme.palette.mode === 'dark'
                  ? 'rgba(30, 41, 59, 0.7)'
                  : 'rgba(241, 245, 249, 0.85)'
                : 'action.hover',
            border: (theme) =>
              `1px solid ${privacyLock ? theme.palette.primary.main : theme.palette.divider}`,
            display: 'flex',
            alignItems: 'flex-start',
            justifyContent: 'space-between',
            gap: 2,
          }}
        >
          <Box sx={{ display: 'flex', gap: 1.5 }}>
            <SecurityIcon
              color={privacyLock ? 'primary' : 'action'}
              sx={{ fontSize: 24, mt: 0.25 }}
            />
            <Box>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <Typography variant="subtitle2" fontWeight="700">
                  Privacy Lock (Post Anonymously)
                </Typography>
                <Chip
                  label={privacyLock ? 'Anonymous' : 'Public'}
                  color={privacyLock ? 'primary' : 'default'}
                  size="small"
                  sx={{ height: 20, fontSize: '0.68rem', fontWeight: 700 }}
                />
              </Box>
              <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.5 }}>
                {accountPrivacyLockActive
                  ? 'Account-wide Privacy Lock is active. Your dummy alias will be used automatically.'
                  : 'Masks your identity from all citizens, officials, and admins. Only your dummy alias will appear publicly.'}
              </Typography>
              {privacyLock && (
                <Box sx={{ mt: 0.75, display: 'inline-flex', alignItems: 'center', gap: 0.5 }}>
                  <Typography variant="caption" fontWeight="700" color="primary.main">
                    Publicly posted as: 🦒 {dummyAlias}
                  </Typography>
                </Box>
              )}
            </Box>
          </Box>
          <FormControlLabel
            control={
              <Switch
                checked={Boolean(privacyLock)}
                onChange={(e) => setPrivacyLock && setPrivacyLock(e.target.checked)}
                disabled={accountPrivacyLockActive}
                color="primary"
              />
            }
            label=""
            sx={{ m: 0 }}
          />
        </Paper>

        <Box sx={{ display: 'flex', justifyContent: 'space-between', mt: 4 }}>
          <Button
            variant="outlined"
            startIcon={<ArrowBackIcon />}
            onClick={onBack}
            disabled={submitting}
          >
            Back
          </Button>

          <Button
            type="submit"
            variant="contained"
            color="primary"
            size="large"
            endIcon={submitting ? <CircularProgress size={20} color="inherit" /> : <SendIcon />}
            disabled={submitting || !title.trim() || !description.trim() || !category}
          >
            {submitting ? 'Submitting Report...' : 'Publish Report'}
          </Button>
        </Box>
      </Box>
    </Box>
  );
};
