import React from 'react';
import {
  Box,
  Button,
  TextField,
  Typography,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  CircularProgress,
  Paper,
  Chip,
  Alert,
} from '@mui/material';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import SendIcon from '@mui/icons-material/Send';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';


export const AutoFillReviewStep = ({
  title,
  setTitle,
  description,
  setDescription,
  category,
  setCategory,
  photoPreview,
  aiSuccess,
  onSubmit,
  onBack,
  submitting,
}) => {
  return (
    <Box sx={{ maxWidth: 650, mx: 'auto' }}>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
        <Typography variant="h6" fontWeight="700">
          Step 2: Review & Submit Report
        </Typography>
        {aiSuccess && (
          <Chip
            icon={<AutoAwesomeIcon fontSize="small" />}
            label="Auto-filled by AI"
            color="secondary"
            size="small"
            sx={{ fontWeight: 600 }}
          />
        )}
      </Box>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
        Review and edit the report details generated by AI before submitting to public record.
      </Typography>

      {!aiSuccess && (
        <Alert severity="info" sx={{ mb: 3 }}>
          AI auto-fill did not return details or was skipped. Please fill in the report details manually.
        </Alert>
      )}

      {/* Photo Summary Thumbnail */}
      {photoPreview && (
        <Paper
          elevation={0}
          sx={{
            p: 1.5,
            mb: 3,
            display: 'flex',
            alignItems: 'center',
            gap: 2,
            border: '1px solid',
            borderColor: 'divider',
            borderRadius: 2,
          }}
        >
          <Box
            component="img"
            src={photoPreview}
            alt="Report photo thumbnail"
            sx={{ width: 80, height: 60, borderRadius: 1, objectFit: 'cover' }}
          />
          <Typography variant="body2" color="text.secondary">
            Photo ready for submission
          </Typography>
        </Paper>
      )}

      <Box component="form" onSubmit={onSubmit} noValidate>
        <TextField
          margin="normal"
          required
          fullWidth
          id="title"
          label="Report Title"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="e.g. Deep Pothole on Main Street near 5th Ave"
          helperText="Provide a short, clear summary of the issue."
        />

        <FormControl fullWidth margin="normal" required>
          <InputLabel id="category-select-label">Category</InputLabel>
          <Select
            labelId="category-select-label"
            id="category"
            value={category}
            label="Category"
            onChange={(e) => setCategory(e.target.value)}
          >
            <MenuItem value="pothole">Pothole</MenuItem>
            <MenuItem value="streetlight">Streetlight</MenuItem>
            <MenuItem value="traffic_light">Traffic Light</MenuItem>
            <MenuItem value="garbage">Garbage / Dumping</MenuItem>
            <MenuItem value="other">Other Infrastructure</MenuItem>
          </Select>
        </FormControl>

        <TextField
          margin="normal"
          required
          fullWidth
          multiline
          rows={4}
          id="description"
          label="Detailed Description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="Describe the problem, hazard potential, and surrounding details..."
        />

        <Box sx={{ display: 'flex', justifyContent: 'space-between', mt: 4 }}>
          <Button
            variant="outlined"
            startIcon={<ArrowBackIcon />}
            onClick={onBack}
            disabled={submitting}
          >
            Back
          </Button>

          <Button
            type="submit"
            variant="contained"
            color="primary"
            size="large"
            endIcon={submitting ? <CircularProgress size={20} color="inherit" /> : <SendIcon />}
            disabled={submitting || !title.trim() || !description.trim() || !category}
          >
            {submitting ? 'Submitting Report...' : 'Publish Report'}
          </Button>
        </Box>
      </Box>
    </Box>
  );
};
