export const DEMO_REPORTS = [
  {
    report_id: 'demo-1',
    reporter_id: 'user-1',
    title: 'Severe Pothole on 5th Avenue Main Crossing',
    description: 'Deep pothole causing traffic slowdown and tire damage near the downtown intersection. Poses hazard for cyclists.',
    category: 'pothole',
    latitude: 37.7749,
    longitude: -122.4194,
    status: 'on_process',
    is_hidden: false,
    like_count: 34,
    comment_count: 8,
    photo_url: '/images/pothole.jpg',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    users: {
      name: 'alex_turner',
      email: 'alex@civicvoice.org',
    },
  },
  {
    report_id: 'demo-2',
    reporter_id: 'user-2',
    title: 'Broken LED Streetlight on Elm Street',
    description: 'The pole streetlight has been completely dark for 4 nights in a row, making the residential pedestrian walk unsafe.',
    category: 'streetlight',
    latitude: 37.7833,
    longitude: -122.4167,
    status: 'budget_allocated',
    is_hidden: false,
    like_count: 52,
    comment_count: 14,
    photo_url: '/images/streetlight.jpg',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    users: {
      name: 'sarah_civic',
      email: 'sarah@civicvoice.org',
    },
  },
  {
    report_id: 'demo-3',
    reporter_id: 'user-3',
    title: 'Malfunctioning Pedestrian Traffic Signal',
    description: 'Walk signal fails to trigger during peak school crossing hours. Children and families have to cross between moving cars.',
    category: 'traffic_light',
    latitude: 37.7699,
    longitude: -122.4467,
    status: 'finished',
    is_hidden: false,
    like_count: 89,
    comment_count: 21,
    photo_url: '/images/traffic_light.jpg?v=2',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    users: {
      name: 'marcus_chen',
      email: 'marcus@civicvoice.org',
    },
  },
  {
    report_id: 'demo-4',
    reporter_id: 'user-4',
    title: 'Overflowing Public Waste Bins at Central Park',
    description: 'Heavy litter spilling onto public footpaths after weekend event. Stray animals scattering garbage into storm drains.',
    category: 'garbage',
    latitude: 37.7651,
    longitude: -122.4221,
    status: 'ordered',
    is_hidden: false,
    like_count: 41,
    comment_count: 6,
    photo_url: '/images/garbage.jpg',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    users: {
      name: 'elena_rodriguez',
      email: 'elena@civicvoice.org',
    },
  },
];
